#####################
# Example open api spec for client api generation.
#####################
openapi: '3.0.2'
info:
  title: Example Api
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /documents:
    get:
      operationId: getDocuments
      summary: Get all documents
      responses:
        '200':
          description: Documents retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Documents'
      security:
        - user: [documents.read]
  /documents/{documentId}:
    get:
      operationId: getDocument
      summary: Get a document by id
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Document retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
      security:
        - user: [documents.read]
    post:
      operationId: uploadDocument
      summary: Update a document by id
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: Document uploaded successfully
      security:
        - user: [documents.write]
components:
  securitySchemes:
    user:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.server.test/oauth2/authorize
          scopes:
            documents.read: Document read scope
            documents.write: Document write scope
            user: User scope
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        content:
          type: string
    Documents:
      type: array
      items:
        $ref: '#/components/schemas/Document'
